[config.wallpaper]
# Whether to set the wallpaper or not

#base command to run for applying  the wallpaper
command = "swww"

arguments = ["img", "--transition-type", "wipe"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

# Hyprlock
[templates.hyprlock]
input_path = '~/.config/matugen/templates/matugen-hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/matugen/matugen-hyprlock.conf'

# Kitty
[templates.kitty]
input_path = '~/.config/matugen/templates/matugen-kitty.conf'
output_path = '~/.config/kitty/matugen/colors-matugen.conf'

[templates.rofi]  
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/matugen/matugen-rofi.rasi'

[templates.waybar]  
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar; waybar &'

# Swaync
[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync.css'
output_path = '~/.config/swaync/matugen/matugen-swaync.css'
post_hook = 'swaync-client -rs'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Qt5
[templates.qt5]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'

# Qt6
[templates.qt6]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'
